name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: os_specific_installs
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
            apt -y install libgpgme-dev libassuan-dev libbtrfs-dev pkg-config
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install gpgme
          fi
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: skopeo --version
